/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeButton: typeof import('./components/HomeButton/index.vue')['default']
    LeftList: typeof import('./components/LeftList/index.vue')['default']
    LoginButton: typeof import('./components/LoginButton/index.vue')['default']
    LoginRegister: typeof import('./components/LoginRegister/index.vue')['default']
    MenuList: typeof import('./components/MenuList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserTip: typeof import('./components/UserTip/index.vue')['default']
  }
}
